#!/usr/bin/env python3
"""One elevation angle over a single fixed scene.

Launched as a subprocess, one instance per GPU. CUDA_VISIBLE_DEVICES must be set
BEFORE any GPU import so Dr.Jit/Mitsuba take full control of that device.

See docs/pipelines.md.
"""

# CRITICAL: set CUDA_VISIBLE_DEVICES *before* any drjit / mitsuba / tf import.
# The launcher (notebook) passes CUDA_VISIBLE_DEVICES via the subprocess env.
# We also honour a --gpu_id arg for documentation/logging purposes.
import os
import sys
from pathlib import Path
import argparse
import json
import time
import gc
import pickle

parser = argparse.ArgumentParser(description="Urban Rician fading sim — single elevation angle")
parser.add_argument("--elevation", type=float, default=None,
                    help="Elevation angle [degrees]. Used directly (with the legacy "
                         "fixed-azimuth TX placement) unless --waypoints_file is given.")
parser.add_argument("--waypoints_file", type=str, default=None,
                    help="Pickle produced by generate_pass_waypoints.py. When given, "
                         "TX position/velocity/elevation all come from one real SGP4 "
                         "pass sample instead of --elevation + assumed azimuth.")
parser.add_argument("--waypoint_index", type=int, default=None,
                    help="Index into waypoints_file['waypoints'] to run. Required if "
                         "--waypoints_file is given.")
parser.add_argument("--gpu_id",    type=int,   default=0,
                    help="Logical GPU index (used for CUDA_VISIBLE_DEVICES if not already set)")
parser.add_argument("--config",    type=str,   required=True,
                    help="Path to sim_config.json")
parser.add_argument("--rx_file",   type=str,   required=True,
                    help="Path to rx_positions.pkl (generated by the notebook)")
parser.add_argument("--output",    type=str,   required=True,
                    help="Output directory for checkpoints and results")
parser.add_argument("--resume",    action="store_true", default=False,
                    help="Resume from checkpoint if one exists")
parser.add_argument("--no-resume", action="store_true", default=False,
                    dest="no_resume",
                    help="Force a fresh start, ignoring any existing checkpoint "
                         "(overrides --resume if both are passed)")
args = parser.parse_args()

if args.waypoints_file is not None:
    if args.waypoint_index is None:
        parser.error("--waypoint_index is required when --waypoints_file is given")
else:
    if args.elevation is None:
        parser.error("either --elevation or (--waypoints_file + --waypoint_index) is required")

# Set GPU visibility before any GPU library imports
if "CUDA_VISIBLE_DEVICES" not in os.environ:
    os.environ["CUDA_VISIBLE_DEVICES"] = str(args.gpu_id)

# GPU-side imports (after CUDA_VISIBLE_DEVICES is locked in)
DRJIT_LIBLLVM = os.environ.get(
    "DRJIT_LIBLLVM_PATH", "/usr/lib/x86_64-linux-gnu/libLLVM-20.so"
)
os.environ.setdefault("DRJIT_LIBLLVM_PATH", DRJIT_LIBLLVM)

import numpy as np
import drjit
from scipy import constants

from sionna.rt import PathSolver

# Local helpers (assumed to be in the same directory)
# Import root is the directory containing Ray_Tracing/, so the
# Ray_Tracing.src.* package paths resolve however this is invoked.
sys.path.insert(0, str(Path(__file__).resolve().parents[3]))
from Ray_Tracing.src.utils.channel_utils  import (rms_delay_spread, rms_angular_spread, complex_channel,
                              split_by_interaction_type,
                              tx_position_from_elevation,
                              tx_position_from_pass_sample, tx_velocity_scene_frame,
                              doppler_mean_rms_from_paths,
                              rms_doppler_spread_hz)
from Ray_Tracing.src.utils.scene_utils    import build_scene_batch, load_rx_positions
from Ray_Tracing.src.utils.orbital_utils  import slant_range_m
from Ray_Tracing.src.utils.checkpoint_utils import (save_checkpoint, load_checkpoint,
                               save_results)
from Ray_Tracing.src.utils.ionospheric_utils import (apply_ionospheric_corrections,
                                sample_faraday_angle,
                                ionospheric_summary)
from Ray_Tracing.src.utils.atmospheric_utils import (compute_atmospheric_effects,
                                apply_atmospheric_corrections,
                                atmospheric_deterministic_summary)

# Load configuration

with open(args.config, "r") as f:
    cfg = json.load(f)

# Verify the patched Sionna is loaded and record it in the results, so every
# run file carries its own provenance. scene_utils re-checks at solve time.
import Ray_Tracing.src.sionna_patch_check as sionna_patch_check
cfg["_SIONNA_PATCH"] = sionna_patch_check.require("run_elevation_sim")
print(f"  {sionna_patch_check.summary_line(cfg['_SIONNA_PATCH'])}")

OUTPUT_DIR              = args.output

# ── Waypoint (real SGP4 pass sample) vs. legacy fixed-elevation mode ─────────
USE_WAYPOINT = args.waypoints_file is not None
if USE_WAYPOINT:
    with open(args.waypoints_file, "rb") as f:
        _wp_data = pickle.load(f)
    WAYPOINT      = _wp_data["waypoints"][args.waypoint_index]
    ELEVATION_DEG = float(WAYPOINT["matched_elev_deg"])
else:
    WAYPOINT      = None
    ELEVATION_DEG = float(args.elevation)
# Priority: --no-resume (CLI) > --resume (CLI) > RESUME_FROM_CHECKPOINT in config > False
_cfg_resume = bool(cfg.get("RESUME_FROM_CHECKPOINT", False))
if args.no_resume:
    RESUME_FROM_CHECKPOINT = False          # explicit CLI override → always fresh
elif args.resume:
    RESUME_FROM_CHECKPOINT = True           # explicit CLI override → always resume
else:
    RESUME_FROM_CHECKPOINT = _cfg_resume    # use value from sim_config.json

# Unpack common config values
FREQUENCY               = float(cfg["FREQUENCY"])
SLANT_DIST_M            = float(cfg["SLANT_DIST_M"]) if cfg.get("SLANT_DIST_M") is not None else None
SCENE_CENTER            = cfg.get("SCENE_CENTER", [0.0, 0.0])
TX_AZIMUTH_DEG          = float(cfg["TX_AZIMUTH_DEG"]) if cfg.get("TX_AZIMUTH_DEG") is not None else 180.0
BATCH_SIZE              = int(cfg["BATCH_SIZE"])
BASE_SAMPLES_PER_SRC    = int(cfg["BASE_SAMPLES_PER_SRC"])
BASE_MAX_PATHS          = int(cfg["BASE_MAX_PATHS"])
N_RX_POSITIONS          = int(cfg["N_RX_POSITIONS"])
RNG_SEED                = int(cfg.get("RNG_SEED", 42))
CHECKPOINT_INTERVAL     = int(cfg.get("CHECKPOINT_INTERVAL", 50))
RAW_SAVE_INTERVAL       = int(cfg.get("RAW_SAVE_INTERVAL", 200))
# Per-path capture for cluster extraction (Method II/III layers). 0 disables.
N_CLUSTER_SAMPLES       = int(cfg.get("N_CLUSTER_SAMPLES", 0))
MAX_CLUSTER_PATHS       = int(cfg.get("MAX_CLUSTER_PATHS", 2000))
# Polarization (actually applied in scene_utils.build_scene_batch per batch;
# read again here only so the run header/log reports what's in effect).
TX_POL_TYPE             = cfg.get("TX_POL_TYPE",      "V")
RX_POL_TYPE             = cfg.get("RX_POL_TYPE",      "V")
POL_BASE_PATTERN        = cfg.get("POL_BASE_PATTERN", "iso")

# Propagation flags
MAX_DEPTH               = int(cfg.get("MAX_DEPTH", 3))
SIM_LOS                 = bool(cfg.get("LOS", True))
SIM_SPECULAR            = bool(cfg.get("SPECULAR_REFLECTION", True))
SIM_DIFFUSE             = bool(cfg.get("DIFFUSE_REFLECTION", True))
SIM_DIFFRACTION         = bool(cfg.get("DIFFRACTION", True))
SIM_EDGE_DIFFRACTION    = bool(cfg.get("EDGE_DIFFRACTION", False))
SIM_REFRACTION          = bool(cfg.get("REFRACTION", False))
BEAMFORMING             = bool(cfg.get("BEAMFORMING", False))
SCENE_RADIUS            = float(cfg.get("SCENE_RADIUS", 100.0))

# ── Ionospheric Monte Carlo model ────────────────────────────────────────────
# IONOSPHERE_ENABLED : master switch (set False to skip all ionospheric effects)
# VTEC_MEAN_TECU     : mean vertical TEC [TECU] for the log-normal distribution
# VTEC_STD_TECU      : std dev of vertical TEC [TECU]
# B_L_TESLA          : mean longitudinal B-field along the path [T]
#
# Per batch, one (vtec, Ω_F) pair is sampled from LN(μ_ln, σ_ln).
# Ω_F is applied as a TX antenna roll offset (pre-RT) so Sionna computes
# Fresnel coefficients for the Faraday-rotated polarisation.
# Group delay and phase advance are applied post-RT to the extracted CIR.
IONOSPHERE_ENABLED      = bool(cfg.get("IONOSPHERE_ENABLED", False))
VTEC_MEAN_TECU          = float(cfg.get("VTEC_MEAN_TECU",  10.0))
VTEC_STD_TECU           = float(cfg.get("VTEC_STD_TECU",   5.0))
B_L_TESLA               = float(cfg.get("B_L_TESLA",       2e-5))
# sigma_h: extra log-space scatter in slant TEC per unit of ln(M(θ)).
# Models the additional variance from spatial TEC heterogeneity along the
# longer slant path at lower elevations.  0.0 = constant CV across elevations.
VTEC_SIGMA_H            = float(cfg.get("VTEC_SIGMA_H",    0.0))

# ── Atmospheric Monte Carlo model ─────────────────────────────────────────────
# ATMOSPHERE_ENABLED   : master switch (set False to skip all atmospheric effects)
# WEATHER_PRESET       : key into WEATHER_PRESETS dict, or None to use explicit params
# ATM_T_K             : surface temperature [K]
# ATM_P_HPA           : surface pressure [hPa]
# ATM_RHO_G_M3        : fixed surface water-vapour density [g/m³]
# RAIN_R_MM_H         : fixed rain rate [mm/h]; 0 = clear sky (no rain)
# ATM_H_STATION_KM    : station height above MSL [km]
# ATM_H_RAIN_KM       : mean rain height (ITU-R P.839, 0°C isotherm + 0.36 km) [km]
# ATM_POL_TILT_DEG    : polarisation tilt angle [deg]; 45° = circular/average
# ATM_D_ANT_M         : receive antenna aperture diameter [m]; 0 = point antenna
# ATM_SCINTILLATION   : include tropospheric scintillation (bool)
ATMOSPHERE_ENABLED      = bool(cfg.get("ATMOSPHERE_ENABLED",   False))
ATM_T_K                 = float(cfg.get("ATM_T_K",             288.15))
ATM_P_HPA               = float(cfg.get("ATM_P_HPA",          1013.25))
ATM_RHO_G_M3            = float(cfg.get("ATM_RHO_G_M3",           7.5))
RAIN_R_MM_H             = float(cfg.get("RAIN_R_MM_H",            0.0))
ATM_H_STATION_KM        = float(cfg.get("ATM_H_STATION_KM",      0.0))
ATM_H_RAIN_KM           = float(cfg.get("ATM_H_RAIN_KM",         3.36))
ATM_POL_TILT_DEG        = float(cfg.get("ATM_POL_TILT_DEG",     45.0))
ATM_D_ANT_M             = float(cfg.get("ATM_D_ANT_M",           0.0))
ATM_SCINTILLATION       = bool(cfg.get("ATM_SCINTILLATION",      True))

# ── Doppler (SGP4 orbital mobility) ──────────────────────────────────────────
# DOPPLER_ENABLED       : master switch — requires USE_WAYPOINT (real TX velocity)
# SCENE_EAST_HEADING_DEG: compass heading of the scene's +X axis (see
#                          orbital_utils.compass_to_scene_azimuth) — must match
#                          the convention generate_pass_waypoints.py assumed.
#
# TX velocity is set directly on the Transmitter object in build_scene_batch()
# and Sionna RT computes each path's exact Doppler shift (Paths.doppler) from
# that velocity and the path's own departure direction during the solve.
# doppler_mean_hz/doppler_rms_hz are a closed-form power-weighted mean/spread
# over those exact per-path values (see channel_utils.doppler_mean_rms_from_paths)
# -- correct on their own, but they never actually modulate `paths.cir()`'s
# output unless it's called with num_time_steps > 1 (Sionna gates the Doppler
# phase-ramp application on that; see Paths.cir). DOPPLER_NUM_TIME_STEPS below
# turns that on, and DOPPLER_OVERSAMPLE_FACTOR sizes the sampling rate needed
# to resolve it without aliasing -- see SAMPLING_FREQUENCY_HZ further down.
DOPPLER_ENABLED         = bool(cfg.get("DOPPLER_ENABLED", False)) and USE_WAYPOINT
DOPPLER_NUM_TIME_STEPS  = int(cfg.get("DOPPLER_NUM_TIME_STEPS", 128))
DOPPLER_OVERSAMPLE_FACTOR = float(cfg.get("DOPPLER_OVERSAMPLE_FACTOR", 10.0))
SCENE_EAST_HEADING_DEG  = float(cfg.get("SCENE_EAST_HEADING_DEG", 90.0))

# Compute TX position (and, for waypoint mode, velocity) for this run.
# BEAM_HALF_ANGLE_RAD is sized per-run from the actual slant distance so the
# ground footprint's narrowest (cross-range) extent always reaches out to
# SCENE_RADIUS -- guaranteeing the whole scene is illuminated at every
# elevation/azimuth, not just matching a target footprint area (which does
# NOT imply containment -- see tx_position_from_elevation's `angle` comment).
# This replaces a single BEAM_ANGLE fixed for the whole sweep (from the
# closest-approach waypoint), which under-illuminated the scene at low
# elevation, starving NLoS ray statistics there and artificially inflating
# K-factor.
if USE_WAYPOINT:
    TX_POS, BEAM_HALF_ANGLE_RAD = tx_position_from_pass_sample(
        WAYPOINT, SCENE_CENTER, SCENE_RADIUS,
        scene_east_heading_deg=SCENE_EAST_HEADING_DEG,
    )
    TX_VEL = tx_velocity_scene_frame(
        WAYPOINT, scene_east_heading_deg=SCENE_EAST_HEADING_DEG,
    )
else:
    # SWEEP_ALTITUDE_KM, if set, replaces the fixed SLANT_DIST_M with the true
    # spherical-Earth range for this elevation.
    _alt = cfg.get("SWEEP_ALTITUDE_KM")
    _sweep_slant_m = float(slant_range_m(_alt, ELEVATION_DEG)) if _alt else SLANT_DIST_M
    TX_POS, BEAM_HALF_ANGLE_RAD = tx_position_from_elevation(
        ELEVATION_DEG, _sweep_slant_m, SCENE_CENTER, SCENE_RADIUS, TX_AZIMUTH_DEG
    )
    TX_VEL = None

# True slant range for this run: the real SGP4 waypoint range in waypoint
# mode (SLANT_DIST_M is a stale legacy placeholder there), else whatever was
# used to place TX_POS above.
SLANT_DIST_ACTUAL_M = float(WAYPOINT["range_m"]) if USE_WAYPOINT else _sweep_slant_m

# Doppler sampling rate: a function of the transmit (carrier) frequency, since
# Doppler shift itself scales linearly with it -- f_D = (FREQUENCY/c)*v. Sized
# off the FULL TX speed (not any single path's smaller LOS/departure-angle
# projection), so it's a conservative bound guaranteed to oversample every
# path's actual per-path Doppler shift, whichever direction it departs in.
# Raising FREQUENCY (e.g. 2 GHz -> 11 GHz) raises this proportionally; with
# DOPPLER_NUM_TIME_STEPS held fixed, the simulated window (steps/sampling_freq)
# then shrinks proportionally too -- exactly matching how much faster the
# fading gets, so it stays inside the quasi-static budget (DOPPLER_WINDOW_S)
# without any separate adjustment.
if DOPPLER_ENABLED:
    DOPPLER_BOUND_HZ = (FREQUENCY / constants.c) * float(np.linalg.norm(TX_VEL))
    SAMPLING_FREQUENCY_HZ = DOPPLER_OVERSAMPLE_FACTOR * max(DOPPLER_BOUND_HZ, 1.0)
else:
    DOPPLER_BOUND_HZ = 0.0
    SAMPLING_FREQUENCY_HZ = 1.0

print(f"\n{'='*64}")
print(f"  run_elevation_sim.py")
print(f"  Elevation : {ELEVATION_DEG:.0f}°")
print(f"  GPU       : {os.environ.get('CUDA_VISIBLE_DEVICES', 'default')}")
print(f"  TX pos    : [{TX_POS[0]/1e3:.2f} km, {TX_POS[1]/1e3:.2f} km, {TX_POS[2]/1e3:.2f} km]")
if USE_WAYPOINT:
    print(f"  Waypoint  : az={WAYPOINT['az_deg']:.2f}°  range={WAYPOINT['range_km']:.1f} km  "
          f"pass_t={WAYPOINT['t_s']:.1f} s  |v|={np.linalg.norm(WAYPOINT['enu_vel_kms']):.3f} km/s")
    print(f"  TX vel    : [{TX_VEL[0]:.1f}, {TX_VEL[1]:.1f}, {TX_VEL[2]:.1f}] m/s (scene frame)")
print(f"  Beam      : half-angle={np.degrees(BEAM_HALF_ANGLE_RAD):.4f}°  "
      f"(sized to SCENE_RADIUS={SCENE_RADIUS:.0f} m at slant={SLANT_DIST_ACTUAL_M/1e3:.2f} km, "
      f"elev={ELEVATION_DEG:.1f}°)")
print(f"  Pol       : TX={TX_POL_TYPE}  RX={RX_POL_TYPE}  base_pattern={POL_BASE_PATTERN}")
if DOPPLER_ENABLED:
    _doppler_window_s = DOPPLER_NUM_TIME_STEPS / SAMPLING_FREQUENCY_HZ
    print(f"  Doppler   : ENABLED  bound={DOPPLER_BOUND_HZ:.0f} Hz  "
          f"sampling={SAMPLING_FREQUENCY_HZ/1e3:.1f} kHz  "
          f"steps={DOPPLER_NUM_TIME_STEPS}  window={_doppler_window_s*1e6:.1f} us")
else:
    print(f"  Doppler   : DISABLED"
          + ("" if USE_WAYPOINT else " (requires --waypoints_file)"))
print(f"  max_depth : {MAX_DEPTH}")
print(f"  LoS={SIM_LOS}  Spec={SIM_SPECULAR}  Diff.refl={SIM_DIFFUSE}  "
      f"Diffr={SIM_DIFFRACTION}  Refr={SIM_REFRACTION}")
if IONOSPHERE_ENABLED:
    print(f"  Ionosphere: Monte Carlo  VTEC~LN(μ={VTEC_MEAN_TECU} TECU, "
          f"σ={VTEC_STD_TECU} TECU)  B_L={B_L_TESLA*1e6:.1f} μT")
    ionospheric_summary(VTEC_MEAN_TECU, VTEC_STD_TECU, FREQUENCY, ELEVATION_DEG, B_L_TESLA)
else:
    print(f"  Ionosphere: DISABLED")
if ATMOSPHERE_ENABLED:
    print(f"  Atmosphere: ρ={ATM_RHO_G_M3} g/m³  R={RAIN_R_MM_H} mm/h  "
          f"Scint={'ON' if ATM_SCINTILLATION else 'OFF'}")
    atmospheric_deterministic_summary(FREQUENCY, ELEVATION_DEG,
                                      rho_g_m3=ATM_RHO_G_M3, R_mm_h=RAIN_R_MM_H,
                                      T_K=ATM_T_K, P_hPa=ATM_P_HPA,
                                      h_station_km=ATM_H_STATION_KM,
                                      h_rain_km=ATM_H_RAIN_KM,
                                      pol_tilt_deg=ATM_POL_TILT_DEG)
else:
    print(f"  Atmosphere: DISABLED")
print(f"{'='*64}\n")

# Load RX positions

nominal_rx_positions, rx_meta = load_rx_positions(args.rx_file)

# Use exactly N_RX_POSITIONS (already sampled in notebook, but clamp if needed)
if len(nominal_rx_positions) > N_RX_POSITIONS:
    nominal_rx_positions = nominal_rx_positions[:N_RX_POSITIONS]
N_ACTUAL = len(nominal_rx_positions)
print(f"  RX positions loaded: {N_ACTUAL:,}")

# Split into batches

pos_batches = [
    nominal_rx_positions[i : i + BATCH_SIZE]
    for i in range(0, N_ACTUAL, BATCH_SIZE)
]
n_batches = len(pos_batches)

# Which receivers get their full per-path data persisted for clustering.
# Seeded independently of the run RNG and of elevation/frequency, so the SAME
# receivers are captured in every sweep -- cluster statistics are then paired
# across elevation and frequency rather than being a fresh resample each time.
if N_CLUSTER_SAMPLES > 0:
    _cs_rng = np.random.default_rng(RNG_SEED + 31337)
    CLUSTER_SAMPLE_IDX = set(
        _cs_rng.choice(N_ACTUAL, size=min(N_CLUSTER_SAMPLES, N_ACTUAL),
                       replace=False).tolist()
    )
else:
    CLUSTER_SAMPLE_IDX = set()

# Checkpoint resume or fresh start

os.makedirs(OUTPUT_DIR, exist_ok=True)

if RESUME_FROM_CHECKPOINT:
    ck = load_checkpoint(OUTPUT_DIR, ELEVATION_DEG)
else:
    ck = None

if ck is not None:
    completed_rx      = ck["completed_rx"]
    start_batch       = completed_rx // BATCH_SIZE
    all_K_power       = list(ck["K_power_ratio"])
    all_K_moments     = list(ck["K_moments"])
    all_tau_rms       = list(ck["tau_rms_mean_s"])
    all_p_los         = list(ck["los_probability"])
    # Graceful fallback for checkpoints saved before the power-split addition
    all_P_los         = list(ck.get("P_los",         [0.0] * completed_rx))
    all_P_specular    = list(ck.get("P_specular",    [0.0] * completed_rx))
    all_P_diffuse     = list(ck.get("P_diffuse",     [0.0] * completed_rx))
    all_P_diffraction = list(ck.get("P_diffraction", [0.0] * completed_rx))
    all_P_refraction  = list(ck.get("P_refraction",  [0.0] * completed_rx))
    all_P_nlos        = list(ck.get("P_nlos",        [0.0] * completed_rx))
    # Ionospheric MC — zero-fill if checkpoint pre-dates this feature
    all_omega_F       = list(ck.get("omega_F",       [0.0] * completed_rx))
    all_vtec_sample   = list(ck.get("vtec_sample",   [0.0] * completed_rx))
    # Atmospheric MC — zero-fill if checkpoint pre-dates this feature
    all_A_gas_db      = list(ck.get("A_gas_db",      [0.0] * completed_rx))
    all_R_sample      = list(ck.get("R_sample_mm_h", [0.0] * completed_rx))
    all_A_rain_db     = list(ck.get("A_rain_db",     [0.0] * completed_rx))
    all_scint_db      = list(ck.get("scint_db",      [0.0] * completed_rx))
    all_atm_total_db  = list(ck.get("atm_total_db",  [0.0] * completed_rx))
    # Doppler (SGP4 waypoint mobility) — zero-fill if checkpoint pre-dates this feature
    all_doppler_mean_hz = list(ck.get("doppler_mean_hz", [0.0] * completed_rx))
    all_doppler_rms_hz  = list(ck.get("doppler_rms_hz",  [0.0] * completed_rx))
    # Time-domain FFT cross-check — zero-fill if checkpoint pre-dates this feature
    all_doppler_mean_hz_td = list(ck.get("doppler_mean_hz_td", [0.0] * completed_rx))
    all_doppler_rms_hz_td  = list(ck.get("doppler_rms_hz_td",  [0.0] * completed_rx))
    # NTN angular spreads -- zero-fill if the checkpoint pre-dates this feature
    all_ASD_deg       = list(ck.get("ASD_deg", [0.0] * completed_rx))
    all_ASA_deg       = list(ck.get("ASA_deg", [0.0] * completed_rx))
    all_ZSD_deg       = list(ck.get("ZSD_deg", [0.0] * completed_rx))
    all_ZSA_deg       = list(ck.get("ZSA_deg", [0.0] * completed_rx))
    cluster_samples   = list(ck.get("cluster_samples", []))
    raw_results       = list(ck["raw_results"])
    print(f"  Resuming from completed_rx = {completed_rx}/{N_ACTUAL}")
else:
    completed_rx      = 0
    start_batch       = 0
    all_K_power       = []
    all_K_moments     = []
    all_tau_rms       = []
    all_p_los         = []
    all_P_los         = []
    all_P_specular    = []
    all_P_diffuse     = []
    all_P_diffraction = []
    all_P_refraction  = []
    all_P_nlos        = []
    all_omega_F       = []
    all_vtec_sample   = []
    # Atmospheric MC: per-receiver records (batch value broadcast to all RX in batch)
    all_A_gas_db      = []
    all_R_sample      = []
    all_A_rain_db     = []
    all_scint_db      = []
    all_atm_total_db  = []
    all_doppler_mean_hz = []
    all_doppler_rms_hz  = []
    all_doppler_mean_hz_td = []
    all_doppler_rms_hz_td  = []
    all_ASD_deg       = []
    all_ASA_deg       = []
    all_ZSD_deg       = []
    all_ZSA_deg       = []
    cluster_samples   = []
    raw_results       = []
    print(f"  Starting fresh run for elevation {ELEVATION_DEG}°")

# Main simulation loop

rng         = np.random.default_rng(seed=RNG_SEED + int(ELEVATION_DEG * 7))
# Separate RNG for ionospheric MC so it doesn't disturb solver/position seeds
rng_iono    = np.random.default_rng(seed=RNG_SEED + int(ELEVATION_DEG * 13) + 99991)
# Separate RNG for atmospheric MC (independent of ionospheric and solver RNGs)
rng_atm     = np.random.default_rng(seed=RNG_SEED + int(ELEVATION_DEG * 17) + 77773)
solver      = PathSolver()
total_start = time.perf_counter()

for batch_idx, rx_batch in enumerate(pos_batches[start_batch:], start=start_batch):

    actual_bs   = len(rx_batch)
    batch_start = time.perf_counter()

    # ── Memory cleanup ─────────────────────────────────────────────────────────
    for _name in ["paths", "amp_np", "tau_np", "inter_np", "scene"]:
        if _name in dir():
            del globals()[_name]
    gc.collect()
    try:
        drjit.flush_malloc_cache()
        drjit.eval()
    except Exception:
        pass

    # ── Sample atmospheric losses for this batch ──────────────────────────────
    # All three effects (gaseous, rain, scintillation) act on the full slant
    # path above the urban scene, so one draw per batch is correct.
    if ATMOSPHERE_ENABLED:
        batch_atm = compute_atmospheric_effects(
            freq_hz               = FREQUENCY,
            elev_deg              = ELEVATION_DEG,
            rho_g_m3              = ATM_RHO_G_M3,
            R_mm_h                = RAIN_R_MM_H,
            rng                   = rng_atm,
            T_K                   = ATM_T_K,
            P_hPa                 = ATM_P_HPA,
            h_station_km          = ATM_H_STATION_KM,
            h_rain_km             = ATM_H_RAIN_KM,
            pol_tilt_deg          = ATM_POL_TILT_DEG,
            D_ant_m               = ATM_D_ANT_M,
            include_scintillation = ATM_SCINTILLATION,
        )
    else:
        batch_atm = {
            "A_gas_db": 0.0, "R_sample_mm_h": 0.0, "A_rain_db": 0.0,
            "scint_db": 0.0, "sigma_scint_db": 0.0, "total_loss_db": 0.0,
        }

    # ── Sample Faraday rotation angle for this batch ───────────────────────────
    if IONOSPHERE_ENABLED:
        batch_omega_F, batch_tec_slant = sample_faraday_angle(
            VTEC_MEAN_TECU, VTEC_STD_TECU,
            FREQUENCY, ELEVATION_DEG, B_L_TESLA,
            rng_iono,
            sigma_h=VTEC_SIGMA_H,
        )
    else:
        batch_omega_F   = 0.0
        batch_tec_slant = 0.0

    # ── Build scene (TX polarisation pre-rotated by Ω_F) ──────────────────────
    # TX velocity (if Doppler is enabled) is set directly on the Transmitter
    # object here -- Sionna RT has no post-hoc "apply velocity to Paths" call
    # in this version; velocity has to be known before the solve, since each
    # path's Doppler shift is derived from its own departure direction at
    # solve time.
    scene, _ = build_scene_batch(
        rx_batch, TX_POS, cfg, omega_F=batch_omega_F,
        tx_velocity=(TX_VEL if DOPPLER_ENABLED else None),
    )

    # ── Solve paths ────────────────────────────────────────────────────────────
    seed = drjit.cuda.ad.UInt(int(rng.integers(1, 1_000_000)))

    paths = solver(
        scene                 = scene,
        max_depth             = MAX_DEPTH,
        los                   = SIM_LOS,
        specular_reflection   = SIM_SPECULAR,
        diffuse_reflection    = SIM_DIFFUSE,
        refraction            = SIM_REFRACTION,
        diffraction           = SIM_DIFFRACTION,
        edge_diffraction      = SIM_EDGE_DIFFRACTION,
        synthetic_array       = False,
        beamforming           = BEAMFORMING,
        beam_angle            = BEAM_HALF_ANGLE_RAD,
        max_num_paths_per_src = BASE_MAX_PATHS,
        samples_per_src       = BASE_SAMPLES_PER_SRC,
        seed                  = seed,
    )

    # Always the cheap single-snapshot call (num_time_steps=1 default).
    # Requesting num_time_steps=DOPPLER_NUM_TIME_STEPS here would make Sionna
    # allocate a [batch_size, ..., max_num_paths_per_src, num_time_steps]
    # tensor for the WHOLE BATCH before any per-RX validity filtering --
    # with BASE_MAX_PATHS/BASE_SAMPLES_PER_SRC in the tens of thousands and
    # num_time_steps=128, that's what blew GPU memory (8 GiB+ in one alloc).
    # The Doppler time series is synthesized per-RX below instead, from the
    # already-filtered, already-tiny per-RX path arrays -- see the
    # doppler_mean_hz_td block.
    amp_np, tau_np = paths.cir(normalize_delays=False, out_type="numpy")
    inter_np         = paths.interactions.numpy()
    # Per-path Doppler shift [Hz], already computed by the solver above from
    # the TX velocity set on the scene and each path's departure direction —
    # same indexing convention as tau_np/amp_np ([rx, rx_ant, tx, tx_ant, path]).
    doppler_np       = paths.doppler.numpy() if DOPPLER_ENABLED else None
    # Per-path departure/arrival angles [rad], same [rx, rx_ant, tx, tx_ant, path]
    # convention as tau_np/amp_np. Needed for the 3GPP angular spreads
    # (ASD/ASA from azimuth, ZSD/ZSA from zenith) and for cluster extraction.
    theta_t_np = paths.theta_t.numpy()
    phi_t_np   = paths.phi_t.numpy()
    theta_r_np = paths.theta_r.numpy()
    phi_r_np   = paths.phi_r.numpy()

    # ── Per-receiver extraction ────────────────────────────────────────────────
    for local_rx in range(actual_bs):
        rx_nom    = rx_batch[local_rx]

        t           = tau_np[local_rx, 0, 0, 0, :]
        a_full      = amp_np[local_rx, 0, 0, 0, :, :]     # [n_paths, num_time_steps]
        # Full interaction tensor across all depths: shape [max_depth, n_paths]
        inter_all   = inter_np[:, local_rx, 0, 0, 0, :]

        valid       = np.any(np.abs(a_full) > 0.0, axis=-1)
        t_v         = t[valid]
        a_full_v    = a_full[valid, :]             # [n_valid_paths, num_time_steps]
        inter_all_v = inter_all[:, valid]          # [max_depth, n_valid_paths]
        doppler_v   = doppler_np[local_rx, 0, 0, 0, :][valid] if DOPPLER_ENABLED else None
        # Same `valid` mask, so these stay index-aligned with t_v / a_v. The
        # iono/atmo corrections below rescale and phase-shift amplitudes but
        # never reorder or drop paths, so the alignment holds all the way to
        # the angular-spread computation.
        theta_t_v   = theta_t_np[local_rx, 0, 0, 0, :][valid]
        phi_t_v     = phi_t_np  [local_rx, 0, 0, 0, :][valid]
        theta_r_v   = theta_r_np[local_rx, 0, 0, 0, :][valid]
        phi_r_v     = phi_r_np  [local_rx, 0, 0, 0, :][valid]

        # ── Post-RT: ionospheric group delay + phase advance ───────────────────
        # Faraday rotation was already applied pre-RT via the TX orientation
        # roll offset (batch_omega_F), so only the free-space delay effects
        # remain to be corrected here. Corrections are quasi-static over the
        # short Doppler window, so the same scalar delay/phase/amplitude
        # adjustment is applied uniformly across all time steps.
        if IONOSPHERE_ENABLED and len(t_v) > 0:
            iono = apply_ionospheric_corrections(
                t_v, a_full_v,
                tec_slant_tecu = batch_tec_slant,  # slant TEC — no re-mapping
                freq_hz        = FREQUENCY,
            )
            t_v      = iono["taus_mod"]
            a_full_v = iono["amps_mod"]

        # ── Post-RT: atmospheric amplitude loss ────────────────────────────────
        # Applied after ionospheric corrections (order is irrelevant since
        # atmospheric loss is a real-valued amplitude scale with no phase term).
        # Delays are unchanged — atmospheric group delay is < 1 ns at GHz.
        if ATMOSPHERE_ENABLED and len(t_v) > 0:
            atm = apply_atmospheric_corrections(
                t_v, a_full_v,
                total_loss_db = batch_atm["total_loss_db"],
            )
            t_v      = atm["taus_mod"]
            a_full_v = atm["amps_mod"]

        # Backward-compatible single-snapshot slice (t=0) feeds all the
        # existing K-factor / delay-spread / power-split logic unchanged.
        a_v = a_full_v[:, 0] if a_full_v.size else a_full_v

        # Power-weighted mean/RMS Doppler spread for this waypoint, computed
        # in closed form from each path's exact Doppler shift + power (see
        # channel_utils.doppler_mean_rms_from_paths) — no time-domain sampling,
        # so no sampling-rate/aliasing concern.
        if DOPPLER_ENABLED and len(t_v) > 0:
            doppler_mean_hz, doppler_rms_hz = doppler_mean_rms_from_paths(doppler_v, a_v)
        else:
            doppler_mean_hz, doppler_rms_hz = 0.0, 0.0

        # Time-domain cross-check: synthesize h(t) on the host from the
        # already-filtered, already-tiny per-RX a_v/doppler_v (NOT from a
        # Sionna-side num_time_steps>1 tensor -- see the cir() call above)
        # and re-derive mean/RMS Doppler via FFT (rms_doppler_spread_hz).
        # a_v is Sionna's own baseband coefficient a_i*exp(-j2*pi*f*tau_i)
        # (Paths.cir's output already includes that delay phase -- see
        # Paths.cir's docstring), so the only additional factor needed to
        # match Sionna's own Doppler formula is the per-path phase ramp
        # exp(j2*pi*f_D,i*t); re-applying exp(-j2*pi*f*tau) here (e.g. via
        # channel_utils.complex_channel_time_series, which assumes its input
        # is the RAW pre-delay-phase coefficient) would double-count that
        # phase and corrupt the coherent sum -- so this sums a_v directly.
        if DOPPLER_ENABLED and DOPPLER_NUM_TIME_STEPS > 1 and len(t_v) > 0:
            t_axis = np.arange(DOPPLER_NUM_TIME_STEPS) / SAMPLING_FREQUENCY_HZ
            a_t = a_v[:, None] * np.exp(1j * 2 * np.pi * doppler_v[:, None] * t_axis[None, :])
            h_t = np.sum(a_t, axis=0)
            doppler_mean_hz_td, doppler_rms_hz_td = rms_doppler_spread_hz(h_t, SAMPLING_FREQUENCY_HZ)
        else:
            doppler_mean_hz_td, doppler_rms_hz_td = 0.0, 0.0

        if len(t_v) > 0:
            # Coherent split — P_los and P_nlos define K = P_los/P_nlos
            pwr         = split_by_interaction_type(t_v, a_v, inter_all_v, FREQUENCY,
                                                     incoherent=False)
            # Incoherent split — per-mechanism breakdown; powers are additive
            # (Σ P_mech_incoherent = P_total_incoherent), so fractions sum to 100 %
            pwr_inc     = split_by_interaction_type(t_v, a_v, inter_all_v, FREQUENCY,
                                                     incoherent=True)
            _, ds        = rms_delay_spread(t_v, a_v)
            # 3GPP TR 38.901 Sec 7.5 power-weighted circular angular spreads.
            # ASD/ZSD are expected to be ~0 for a satellite link (the TX
            # subtends ~0.03 deg across this scene) -- that reproduces the
            # TR 38.811 NOTE 8 convention rather than indicating a bug.
            _, ASD_rad   = rms_angular_spread(phi_t_v,   a_v)
            _, ASA_rad   = rms_angular_spread(phi_r_v,   a_v)
            _, ZSD_rad   = rms_angular_spread(theta_t_v, a_v)
            _, ZSA_rad   = rms_angular_spread(theta_r_v, a_v)
            h_total      = complex_channel(t_v, a_v, FREQUENCY)
            P_los        = pwr["P_los"]
            P_nlos       = pwr["P_nlos"]
            has_los_flag = pwr["has_los"]
        else:
            pwr = pwr_inc = {
                "P_los": 0.0, "P_specular": 0.0, "P_diffuse": 0.0,
                "P_diffraction": 0.0, "P_refraction": 0.0, "P_nlos": 0.0,
                "has_los": False,
            }
            P_los = P_nlos = ds = 0.0
            ASD_rad = ASA_rad = ZSD_rad = ZSA_rad = 0.0
            h_total      = 0j
            has_los_flag = False

        K_pr  = P_los / (P_nlos + 1e-30)
        h_env = float(np.abs(h_total))
        ASD_deg, ASA_deg = np.degrees(ASD_rad), np.degrees(ASA_rad)
        ZSD_deg, ZSA_deg = np.degrees(ZSD_rad), np.degrees(ZSA_rad)

        all_K_power      .append(float(K_pr))
        all_K_moments    .append(float('nan'))
        all_p_los        .append(1.0 if has_los_flag else 0.0)
        all_tau_rms      .append(float(ds))
        all_P_los        .append(float(P_los))
        # Store INCOHERENT per-mechanism powers so they are additive in charts
        all_P_specular   .append(float(pwr_inc["P_specular"]))
        all_P_diffuse    .append(float(pwr_inc["P_diffuse"]))
        all_P_diffraction.append(float(pwr_inc["P_diffraction"]))
        all_P_refraction .append(float(pwr_inc["P_refraction"]))
        all_P_nlos       .append(float(P_nlos))
        # Ionospheric MC: record the batch-level Ω_F and VTEC for this receiver
        all_omega_F      .append(float(batch_omega_F))
        all_vtec_sample  .append(float(batch_tec_slant))
        # Atmospheric MC: record batch-level losses for this receiver
        all_A_gas_db     .append(float(batch_atm["A_gas_db"]))
        all_R_sample     .append(float(batch_atm["R_sample_mm_h"]))
        all_A_rain_db    .append(float(batch_atm["A_rain_db"]))
        all_scint_db     .append(float(batch_atm["scint_db"]))
        all_atm_total_db .append(float(batch_atm["total_loss_db"]))
        # Doppler (SGP4 waypoint mobility): per-receiver RMS Doppler spread
        all_doppler_mean_hz.append(float(doppler_mean_hz))
        all_doppler_rms_hz .append(float(doppler_rms_hz))
        # Time-domain FFT cross-check of the two lines above
        all_doppler_mean_hz_td.append(float(doppler_mean_hz_td))
        all_doppler_rms_hz_td .append(float(doppler_rms_hz_td))
        all_ASD_deg      .append(float(ASD_deg))
        all_ASA_deg      .append(float(ASA_deg))
        all_ZSD_deg      .append(float(ZSD_deg))
        all_ZSA_deg      .append(float(ZSA_deg))

        # ── Per-path capture for cluster extraction ───────────────────────────
        # Kept OUT of raw_results deliberately: raw_results is consumed by
        # plot_utils.plot_cir / results_analysis.ipynb with a fixed schema, is
        # gated on a different interval, and carries no per-path angles.
        # Clustering needs delay AND angle jointly, for many more receivers.
        #
        # Delays are split into a float64 epoch + float32 excess delay: absolute
        # delays are ~1.7 ms at LEO slant range, where float32 quantises at
        # ~0.17 ns -- the same order as the 3GPP cluster DS (1.6 ns) we intend to
        # measure. The excess delays carry sub-ps resolution at half the bytes.
        if completed_rx in CLUSTER_SAMPLE_IDX and len(t_v) > 0:
            _p_order = np.argsort(np.abs(a_v) ** 2)[::-1][:MAX_CLUSTER_PATHS]
            _tau0 = float(np.min(t_v[_p_order]))
            cluster_samples.append({
                "rx_index"     : int(completed_rx),
                "rx_nominal"   : np.asarray(rx_nom, dtype=np.float32),
                "tau0_s"       : _tau0,
                "dtau_s"       : (t_v[_p_order] - _tau0).astype(np.float32),
                "amp"          : a_v[_p_order].astype(np.complex64),
                "theta_t"      : theta_t_v[_p_order].astype(np.float32),
                "phi_t"        : phi_t_v  [_p_order].astype(np.float32),
                "theta_r"      : theta_r_v[_p_order].astype(np.float32),
                "phi_r"        : phi_r_v  [_p_order].astype(np.float32),
                # primary interaction type per path -> lets the dominant/diffuse
                # split and the diffuse-sensitivity check be done at analysis time
                "prim_type"    : np.asarray(pwr["primary_type"])[_p_order].astype(np.int8),
                "has_los"      : bool(has_los_flag),
                "n_paths_total": int(len(t_v)),
            })

        # Save raw results at regular intervals
        if (completed_rx + 1) % RAW_SAVE_INTERVAL == 0:
            raw_results.append({
                "rx_nominal"   : list(rx_nom),
                "taus"         : t_v.copy(),
                "amps"         : a_v.copy(),
                "inter_d0"     : inter_all_v[0].copy() if len(t_v) > 0 else np.array([], dtype=int),
                "P_los"        : float(P_los),
                "P_scat"       : float(P_nlos),       # kept for backward compat
                "P_specular"   : float(pwr["P_specular"]),
                "P_diffuse"    : float(pwr["P_diffuse"]),
                "P_diffraction": float(pwr["P_diffraction"]),
                "P_refraction" : float(pwr["P_refraction"]),
                "P_nlos"       : float(P_nlos),
                "tau_rms_s"    : float(ds),
                "h_env"        : float(h_env),
                "has_los"      : bool(has_los_flag),
                "omega_F_rad"  : float(batch_omega_F),
                "vtec_tecu"    : float(batch_tec_slant),
                # Atmospheric MC fields
                "A_gas_db"     : float(batch_atm["A_gas_db"]),
                "R_sample_mm_h": float(batch_atm["R_sample_mm_h"]),
                "A_rain_db"    : float(batch_atm["A_rain_db"]),
                "scint_db"     : float(batch_atm["scint_db"]),
                "atm_total_db" : float(batch_atm["total_loss_db"]),
                # Doppler fields (SGP4 waypoint mobility)
                "doppler_mean_hz": float(doppler_mean_hz),
                "doppler_rms_hz" : float(doppler_rms_hz),
                "doppler_mean_hz_td": float(doppler_mean_hz_td),
                "doppler_rms_hz_td" : float(doppler_rms_hz_td),
                "waypoint_az_deg": float(WAYPOINT["az_deg"]) if USE_WAYPOINT else None,
                "waypoint_range_km": float(WAYPOINT["range_km"]) if USE_WAYPOINT else None,
            })

        completed_rx += 1

    # ── Batch summary ──────────────────────────────────────────────────────────
    Plos_batch  = np.array(all_P_los[-actual_bs:])
    Pnlos_batch = np.array(all_P_nlos[-actual_bs:])
    Pdiffuse_batch  = np.array(all_P_diffuse[-actual_bs:])
    Pdiffraction_batch  = np.array(all_P_diffraction[-actual_bs:])
    Pspecular_batch  = np.array(all_P_specular[-actual_bs:])
    # Ensemble K = E[P_los] / E[P_nlos]  (correct ratio-of-means estimator)
    # This is more stable than averaging per-receiver K values, which can be
    # enormous for receivers with near-zero NLOS power (especially at max_depth=1).
    mean_Plos  = float(np.mean(Plos_batch))
    mean_Pnlos = float(np.mean(Pnlos_batch))
    K_mean_dB   = 10.0 * np.log10(mean_Plos / (mean_Pnlos + 1e-30) + 1e-30)

    elapsed    = time.perf_counter() - batch_start
    total_e    = time.perf_counter() - total_start
    
    # Power breakdown — incoherent, LoS receivers only, ratio-of-means
    _P_total_inc = Plos_batch + Pspecular_batch + Pdiffuse_batch + Pdiffraction_batch
    _mean_tot    = float(np.mean(_P_total_inc))
    _frac_los    = float(np.mean(Plos_batch))   / _mean_tot * 100
    _frac_spec   = float(np.mean(Pspecular_batch))  / _mean_tot * 100
    _frac_diff   = float(np.mean(Pdiffuse_batch))  / _mean_tot * 100
    _frac_diffr  = float(np.mean(Pdiffraction_batch)) / _mean_tot * 100

    
    print()

    iono_str = f"  Ω_F={np.degrees(batch_omega_F):.1f}°  TEC={batch_tec_slant:.1f} TECU" \
               if IONOSPHERE_ENABLED else ""
    atm_str  = (f"  A_gas={batch_atm['A_gas_db']:.2f} dB"
                f"  A_rain={batch_atm['A_rain_db']:.2f} dB (R={batch_atm['R_sample_mm_h']:.1f} mm/h)"
                f"  scint={batch_atm['scint_db']:.2f} dB"
                f"  tot={batch_atm['total_loss_db']:.2f} dB") \
               if ATMOSPHERE_ENABLED else ""
    print(
        f"  [elev={ELEVATION_DEG:.0f}°]  "
        f"done={completed_rx}/{N_ACTUAL}  "
        f"K_mean={K_mean_dB:.1f} dB   "
        f'P_los: {_frac_los  :6.2f}     %'
        f'P_specular: {_frac_spec :6.2f}    %'
        f'P_diffuse: {_frac_diff :6.2f}     %'
        f'P_diffraction: {_frac_diffr:6.2f}     %'
        f"batch={elapsed:.1f}s  total={total_e/3600:.2f}h"
        f"{iono_str}{atm_str}"
    )
    sys.stdout.flush()

    # ── Checkpoint ────────────────────────────────────────────────────────────
    if (batch_idx + 1) % CHECKPOINT_INTERVAL == 0 or completed_rx == N_ACTUAL:
        ck_path = save_checkpoint(
            output_dir     = OUTPUT_DIR,
            elevation_deg  = ELEVATION_DEG,
            completed_rx   = completed_rx,
            total_rx       = N_ACTUAL,
            batch_size     = BATCH_SIZE,
            frequency      = FREQUENCY,
            tx_pos         = TX_POS,
            slant_dist_m   = SLANT_DIST_ACTUAL_M,
            cfg            = cfg,
            K_power_ratio  = all_K_power,
            K_moments      = all_K_moments,
            tau_rms_mean_s = all_tau_rms,
            los_probability= all_p_los,
            P_los          = all_P_los,
            P_specular     = all_P_specular,
            P_diffuse      = all_P_diffuse,
            P_diffraction  = all_P_diffraction,
            P_refraction   = all_P_refraction,
            P_nlos         = all_P_nlos,
            omega_F        = all_omega_F,
            vtec_sample    = all_vtec_sample,
            A_gas_db       = all_A_gas_db,
            R_sample_mm_h  = all_R_sample,
            A_rain_db      = all_A_rain_db,
            scint_db       = all_scint_db,
            atm_total_db   = all_atm_total_db,
            doppler_mean_hz = all_doppler_mean_hz,
            doppler_rms_hz  = all_doppler_rms_hz,
            doppler_mean_hz_td = all_doppler_mean_hz_td,
            doppler_rms_hz_td  = all_doppler_rms_hz_td,
            ASD_deg        = all_ASD_deg,
            ASA_deg        = all_ASA_deg,
            ZSD_deg        = all_ZSD_deg,
            ZSA_deg        = all_ZSA_deg,
            cluster_samples= cluster_samples,
            raw_results    = raw_results,
        )
        print(f"  ✓ checkpoint → {ck_path}")
        sys.stdout.flush()

# Save final results

results_path = save_results(
    output_dir           = OUTPUT_DIR,
    elevation_deg        = ELEVATION_DEG,
    nominal_rx_positions = nominal_rx_positions[:N_ACTUAL],
    K_power_ratio        = all_K_power,
    K_moments            = all_K_moments,
    tau_rms_mean_s       = all_tau_rms,
    los_probability      = all_p_los,
    P_los                = all_P_los,
    P_specular           = all_P_specular,
    P_diffuse            = all_P_diffuse,
    P_diffraction        = all_P_diffraction,
    P_refraction         = all_P_refraction,
    P_nlos               = all_P_nlos,
    omega_F              = all_omega_F,
    vtec_sample          = all_vtec_sample,
    A_gas_db             = all_A_gas_db,
    R_sample_mm_h        = all_R_sample,
    A_rain_db            = all_A_rain_db,
    scint_db             = all_scint_db,
    atm_total_db         = all_atm_total_db,
    doppler_mean_hz      = all_doppler_mean_hz,
    doppler_rms_hz       = all_doppler_rms_hz,
    doppler_mean_hz_td   = all_doppler_mean_hz_td,
    doppler_rms_hz_td    = all_doppler_rms_hz_td,
    ASD_deg              = all_ASD_deg,
    ASA_deg              = all_ASA_deg,
    ZSD_deg              = all_ZSD_deg,
    ZSA_deg              = all_ZSA_deg,
    cluster_samples      = cluster_samples,
    raw_results          = raw_results,
    cfg                  = cfg,
    tx_pos               = TX_POS,
    slant_dist_m         = SLANT_DIST_ACTUAL_M,
)

total_elapsed = time.perf_counter() - total_start
print(f"\n{'='*64}")
print(f"  Elevation {ELEVATION_DEG:.0f}° — COMPLETE")
print(f"  Elapsed   : {total_elapsed/3600:.2f} h  ({total_elapsed:.1f} s)")
print(f"  Results   : {results_path}")
print(f"{'='*64}\n")
